- name: COpy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: latest

- name: Load Master Data
  ansible.builtin.shell: mongosh --host 172.31.23.251 </app/db/master-data.js


#- name: Load MySQL schema
#  when: schema_setup == "mysql"
#  block:
#    - name: Install mysql Client
#      ansible.builtin.dnf:
#        name: mysql
#        state: latest
#
#    - name: Load Master Data
#      ansible.builtin.shell: mysql -h mysql.{{ env }}.rdevopsb80.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
#      loop: "{{schema_files}}"