
- name: Copy mongo config file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install the latest version of mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest

- name: search and replace mongo config file 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/yum.repos.d/mongo.repo
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Mongodb Service
  ansible.builtin.systemd_service:
    state: restarted
    name: mongod
    enabled: true
